### ISSUE TITLE
NVMes do not seem to work

### ISSUE THREAD

**Issue by kohend** [slowpeek/hddtemp#1]
It seems that with my NVMe device I get "Temperature" instead of "Current Temperature" in smartctl, which makes the script fail to report the information for it.

**Comment by slowpeek** [comment]
@kohend Could you provide output of

```
sudo smartctl -i -l scttempsts YOUR_DEVICE_HERE | grep -i temperature
```

**Comment by kohend** [comment]
This should be all of the output you'll need, scttempsts supports only ATA devices, it seems.
```
$sudo smartctl -ai -l scttempsts /dev/nvme0n1 | grep -i KINGSTON
Model Number:                       KINGSTON SNV2S2000G
$ sudo smartctl -i -l scttempsts /dev/nvme0n1 | grep -i temp
$ sudo smartctl -ai -l scttempsts /dev/nvme0n1 | grep -i temp
Warning  Comp. Temp. Threshold:     83 Celsius
Critical Comp. Temp. Threshold:     90 Celsius
Temperature:                        41 Celsius
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0
Thermal Temp. 1 Total Time:         4
```

**Comment by slowpeek** [comment]
Looking into smartctl sources I see there are different output formats for ata, nvme and scsi devices.

Try this branch https://github.com/slowpeek/hddtemp/tree/fi-1

**Comment by slowpeek** [comment]
The changes from fi-1 branch look like OK for me. I merged it into master and ... the branch is gone!
