### ISSUE TITLE
Error while using --classic parameter

### ISSUE THREAD

**Issue by jeanpaulrh** [slowpeek/hddtemp#6]
Hi, and thanks for your script.
I'm trying to use it instead of the original hddtemp with librenms.
I think that I have to use the --classic switch, but I get an error:

`[g9 ssh][me]:~/hddtemp-0.2.4>sudo ./hddtemp-lt --classic`
`iconv: illegal input sequence at position 0`

**Comment by slowpeek** [comment]
Thanks for the report! I overlooked the case when there is no degree symbol in the current locale:

    > LC_ALL=C iconv -f utf-8 <<< $'\xc2\xb0'
    iconv: illegal input sequence at position 0

The original tool falls back to a space in the case. Since 0.2.5, hddtemp-lt does the same.
